### PR TITLE
Feature/require

### PR DESCRIPTION
**Pull request by jlconlin**
This Pull Request implements two templates to help with SFINAE.

### CODE REVIEW

**Comment by jlconlin** [comment]
Several of the tests fail and I'm not sure why. It seems that the templates return the opposite of what we want.

**Review by whaeck — APPROVED** [review]
I normally don't work on Sunday, but you insisted ...

**Comment by jlconlin** [comment]
Thank you, @whaeck

**Comment by apmccartney** [comment]
The coverage was broken in this pull request. Why was this approved? Why was it merged? @whaeck @jlconlin

**Comment by jlconlin** [comment]
We've gotten lax because our tools are often unreliable.

**Pull request merged**
